Include pod UID and container name as optional trace labels
linkerd/linkerd2-proxy pull request #3483
Opened 2024-12-20 16:45 UTC by sfleen

It's useful to include these fields in the trace span attributes to help correlate traffic within a cluster.

This propagates these labels through the trace initialization, similar to how we handle the service name (and other labels that last for the entire pod lifetime).

See https://github.com/linkerd/linkerd2/pull/13501 for the corresponding control plane change.

2024-12-20 16:54 UTC, cratelyn commented
you've been clippy'ed :paperclip: :scream_cat: 

```
Error: error: this function has too many arguments (8/7)
  --> linkerd/app/src/trace_collector/otel_collector.rs:21:1
   |
21 | / pub(super) fn create_collector<S>(
22 | |     addr: ControlAddr,
23 | |     hostname: Option<String>,
24 | |     pod_uid: Option<String>,
...  |
29 | |     legacy_metrics: metrics::Registry,
30 | | ) -> EnabledCollector
   | |_____________________^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#too_many_arguments
   = note: `-D clippy::too-many-arguments` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::too_many_arguments)]`
```

2024-12-20 16:58 UTC, cratelyn approved these changes
besides the note about clippy lints above, this looks like a good PR to me. this should be a nice improvement to our traces!

2024-12-20 16:58 UTC, cratelyn commented on linkerd/app/src/env.rs
> +const ENV_POD_CONTAINER_NAME: &str = "_pod_containerName";
the case here is mildly surprising to me, but that's an implementation detail that i'll consider out of scope for a pr in the proxy.

2025-01-06 13:39 UTC, sfleen commented on linkerd/app/src/env.rs
> +const ENV_POD_CONTAINER_NAME: &str = "_pod_containerName";
It's a little odd to me too, but this is the convention that the control plane uses for populating k8s metadata and I didn't see a strong reason to deviate from that.

2025-01-06 18:15 UTC, olix0r requested changes

2025-01-06 18:15 UTC, olix0r commented on linkerd/app/src/env.rs
> +const ENV_POD_CONTAINER_NAME: &str = "_pod_containerName";
We've generally been pretty adamant (and successful) about not leaking kubernetes concepts (pods, containers, uids, etc) into the proxy's codebase.

You may notice that we load a bunch of attributes from a file at starttime:

https://github.com/linkerd/linkerd2-proxy/pull/3483/files#diff-0ee25f0088036de1851c9f218f1abb2fd0c4abecefe846112c34c6533b2267ccR840-R845

is it possible to encode these attributes into this file so the proxy doesn't need special casing for them?

2025-01-09 21:08 UTC, sfleen commented on linkerd/app/src/env.rs
> +const ENV_POD_CONTAINER_NAME: &str = "_pod_containerName";
AFAICT, the downward API doesn't let you encode more than one field ref in a single file, nor does it give you particularly good control over the keys for the values (unless you're using labels or annotations, and I'd rather not dump all of those for a pod into each trace).

That being said, I think we can still encode these through environment variables as a list of arbitrary extra fields to add. Thoughts on https://github.com/linkerd/linkerd2/pull/13544?

2025-01-13 19:59 UTC, sfleen commented on linkerd/app/src/env.rs
> +const ENV_POD_CONTAINER_NAME: &str = "_pod_containerName";
Cool, I've updated this PR to reflect those changes to the attributes, PTAL

2025-01-30 20:35 UTC, olix0r approved these changes

2025-01-30 20:37 UTC, merged